## Superstore sales data analysis using AQL

## Project Overview

This project analysis a retail superstore dataset using SQL queries.The goal is to SQL understand sales performance, customer behavior and product trends.

In [1]:
import sqlite3
import pandas as pd

In [6]:
df=pd.read_csv("superstore.csv")
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,12/6/2016,16/6/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

## SQL dataset create

In [8]:
conn=sqlite3.connect("superstore.db")
df.to_sql("sales",conn,if_exists="replace",index=False)

9994

## Analysis Queries

## 1] Total sales

In [9]:
query = """
SELECT SUM(sales)AS tota_sales
FROM sales
"""
pd.read_sql(query,conn)

     tota_sales
0  2.297201e+06

## 2] Total Profit

In [10]:
query ="""
SELECT SUM(profit)AS total_profit
FROM sales
"""
pd.read_sql_query(query,conn)

   total_profit
0   286397.0217

## 3] Category Wise Sales

In [11]:
query ="""
SELECT category,
sum(sales)AS total_sales
FROM sales
GROUP BY category
ORDER BY total_sales DESC
"""
pd.read_sql_query(query,conn)

          Category  total_sales
0       Technology  836154.0330
1        Furniture  741999.7953
2  Office Supplies  719047.0320

## 4] Sub-Category Sales

In [12]:
query="""
SELECT"Sub-Category",
SUM(sales)AS total_sales
FROM sales
GROUP BY "Sub-Category"
ORDER BY total_sales DESC
"""
pd.read_sql_query(query,conn)

   Sub-Category  total_sales
0        Phones  330007.0540
1        Chairs  328449.1030
2       Storage  223843.6080
3        Tables  206965.5320
4       Binders  203412.7330
5      Machines  189238.6310
6   Accessories  167380.3180
7       Copiers  149528.0300
8     Bookcases  114879.9963
9    Appliances  107532.1610
10  Furnishings   91705.1640
11        Paper   78479.2060
12     Supplies   46673.5380
13          Art   27118.7920
14    Envelopes   16476.4020
15       Labels   12486.3120
16    Fasteners    3024.2800

## 5] Region Wise Sales

In [13]:
query="""
SELECT Region,
SUM(Sales)AS total_sales
FROM sales
GROUP BY Region
"""
pd.read_sql_query(query,conn)

    Region  total_sales
0  Central  501239.8908
1     East  678781.2400
2    South  391721.9050
3     West  725457.8245

## 6] Top 10 Products

In [14]:
query="""
SELECT"Product Name",
SUM(Sales)AS total_sales
FROM sales
GROUP BY "Product Name"
ORDER BY total_sales DESC
LIMIT 10
"""
pd.read_sql_query(query,conn)

                                        Product Name  total_sales
0              Canon imageCLASS 2200 Advanced Copier    61599.824
1  Fellowes PB500 Electric Punch Plastic Comb Bin...    27453.384
2  Cisco TelePresence System EX90 Videoconferenci...    22638.480
3       HON 5400 Series Task Chairs for Big and Tall    21870.576
4         GBC DocuBind TL300 Electric Binding System    19823.479
5   GBC Ibimaster 500 Manual ProClick Binding System    19024.500
6               Hewlett Packard LaserJet 3310 Copier    18839.686
7  HP Designjet T520 Inkjet Large Format Printer ...    18374.895
8          GBC DocuBind P400 Electric Binding System    17965.068
9        High Speed Automatic Electric Letter Opener    17030.312

## 7]Top Customers

In [18]:
query="""
SELECT "Customer Name",
SUM(Sales)AS total_spent
FROM sales
GROUP BY "Customer Name"
ORDER BY total_spent DESC
LIMIT 10
"""
pd.read_sql_query(query,conn)

        Customer Name  total_spent
0         Sean Miller    25043.050
1        Tamara Chand    19052.218
2        Raymond Buch    15117.339
3        Tom Ashbrook    14595.620
4       Adrian Barton    14473.571
5        Ken Lonsdale    14175.229
6        Sanjit Chand    14142.334
7        Hunter Lopez    12873.298
8        Sanjit Engle    12209.438
9  Christopher Conant    12129.072

## 8] Average Sales per Order

In [20]:
query="""
SELECT AVG(Sales)AS avg_sales
FROM sales
"""
pd.read_sql(query,conn)

    avg_sales
0  229.858001

## 9] Highest Profit Products

In [22]:
query="""
SELECT"Product Name",
SUM(Profit)AS total_profit
FROM sales
GROUP BY "Product Name"
ORDER BY total_profit DESC
LIMIT 10
"""
pd.read_sql_query(query,conn)

                                        Product Name  total_profit
0              Canon imageCLASS 2200 Advanced Copier    25199.9280
1  Fellowes PB500 Electric Punch Plastic Comb Bin...     7753.0390
2               Hewlett Packard LaserJet 3310 Copier     6983.8836
3                 Canon PC1060 Personal Laser Copier     4570.9347
4  HP Designjet T520 Inkjet Large Format Printer ...     4094.9766
5                  Ativa V4110MDD Micro-Cut Shredder     3772.9461
6   3D Systems Cube Printer, 2nd Generation, Magenta     3717.9714
7  Plantronics Savi W720 Multi-Device Wireless He...     3696.2820
8               Ibico EPK-21 Electric Binding System     3345.2823
9                  Zebra ZM400 Thermal Label Printer     3343.5360

## 10] Loss Marketing Products

In [25]:
query="""
SELECT"Product Name",
SUM(Profit)AS total_profit
FROM sales
GROUP BY "Product Name"
HAVING total_profit < 0
ORDER BY total_profit
"""
pd.read_sql_query(query,conn)

                                          Product Name  total_profit
0            Cubify CubeX 3D Printer Double Head Print -8.879970e+03
1            Lexmark MX611dhe Monochrome Laser Printer -4.589973e+03
2            Cubify CubeX 3D Printer Triple Head Print -3.839990e+03
3    Chromcraft Bull-Nose Wood Oval Conference Tabl... -2.876116e+03
4    Bush Advantage Collection Racetrack Conference... -1.934398e+03
..                                                 ...           ...
297                                   Rubber Band Ball -2.992000e-01
298  Acco PRESSTEX Data Binder with Storage Hooks, ... -1.614000e-01
299                           Global Super Steno Chair -4.440892e-15
300        Avery Trapezoid Extra Heavy Duty 4" Binders -3.552714e-15
301                     Premier Electric Letter Opener -3.552714e-15

[302 rows x 2 columns]

## Insights
1] Technology category generates highest sales
2] Some products generate negative profit
3] Few customers contribute large revenue
4] West region has strong sales performance

## Conclusion

In this project,we analyzed the Superstore sales data using SQL queries.We identified top products,top customers and sales performance by category and region.The analysis help